#
# Copyright (c) Huawei Technologies Co., Ltd. 2024. All rights reserved.
#



olc.sdk.domain=olc
olc.sdk.service=olc
olc.sdk.control.switch=on
olc.config.dynamic.switch=on
olc.sdk.config.stub=jsonfile
olc.stub.jsonfile.name=olc.json
olc.config.collector.interval=10000
olc.config.dynamic.refresh.period=2000
olc.log.alarm.switch=off
olc.sdk.reporter.switch=on
olc.sdk.reporter.stub=aom
olc.sdk.kpi.upload.period=60000
olc.sdk.statistic.intervalInSec=60
#dcs
olc.redis.nodeList=${OLC_REDIS_NODE_LIST:${REDIS_CLUSTER_NODES}}
olc.redis.passwd=${REDIS_PASSWORD}
#centerdecision,redis
olc.sdk.decision.stub=redis

#olc.log.independent=on
#olc.log.appender=console
#olc.log.level=info
# redis.mode: alone cluster or sentinel
olc.config.redis.mode=${OLC_CONFIG_REDIS_MODE:cluster}
olc.config.encryptor.name=OlcDecrypt