# 基础配置项
server.port=6001
SERVICE_NAME=XDMLocal
APP_ID=497bc30622bb434c9096c34d1ba38f02
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=123456
jasypt.encryptor.password=

# 手工部署时额外配置
xdm.tx-distributor.discovery-type=static
xdm.tx-distributor.static.instance-secure=false
xdm.tx-distributor.static.instances=127.0.0.1:8003
